"""
Merge manually fetched MaxPreps data with existing weekly rankings
"""
import json
from datetime import datetime

# MaxPreps data fetched manually via WebFetch
maxpreps_data = {
    "uil": {
        "6A": [{"rank": 1, "team_name": "Little Elm", "wins": 18, "losses": 2, "record": "18-2"}, {"rank": 2, "team_name": "Seven Lakes", "wins": 21, "losses": 0, "record": "21-0"}, {"rank": 3, "team_name": "Brennan", "wins": 15, "losses": 3, "record": "15-3"}, {"rank": 4, "team_name": "North Crowley", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 5, "team_name": "Steele", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 6, "team_name": "Clear Brook", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 7, "team_name": "Plano East", "wins": 18, "losses": 4, "record": "18-4"}, {"rank": 8, "team_name": "North Shore", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 9, "team_name": "Cypress Springs", "wins": 18, "losses": 3, "record": "18-3"}, {"rank": 10, "team_name": "Pearland", "wins": 16, "losses": 2, "record": "16-2"}, {"rank": 11, "team_name": "Plano", "wins": 17, "losses": 4, "record": "17-4"}, {"rank": 12, "team_name": "Atascocita", "wins": 12, "losses": 6, "record": "12-6"}, {"rank": 13, "team_name": "Dickinson", "wins": 15, "losses": 5, "record": "15-5"}, {"rank": 14, "team_name": "Clemens", "wins": 18, "losses": 3, "record": "18-3"}, {"rank": 15, "team_name": "Westlake", "wins": 16, "losses": 5, "record": "16-5"}, {"rank": 16, "team_name": "Grand Prairie", "wins": 14, "losses": 3, "record": "14-3"}, {"rank": 17, "team_name": "Judson", "wins": 17, "losses": 5, "record": "17-5"}, {"rank": 18, "team_name": "Tompkins", "wins": 15, "losses": 4, "record": "15-4"}, {"rank": 19, "team_name": "Bowie", "wins": 20, "losses": 2, "record": "20-2"}, {"rank": 20, "team_name": "Fort Bend Hightower", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 21, "team_name": "Round Rock Westwood", "wins": 17, "losses": 2, "record": "17-2"}, {"rank": 22, "team_name": "Duncanville", "wins": 10, "losses": 4, "record": "10-4"}, {"rank": 23, "team_name": "Klein Oak", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 24, "team_name": "Heights", "wins": 16, "losses": 5, "record": "16-5"}, {"rank": 25, "team_name": "Fort Bend Travis", "wins": 16, "losses": 3, "record": "16-3"}],
        "5A": [{"rank": 1, "team_name": "Heritage", "wins": 15, "losses": 2, "record": "15-2"}, {"rank": 2, "team_name": "Beaumont United", "wins": 18, "losses": 1, "record": "18-1"}, {"rank": 3, "team_name": "Mansfield Summit", "wins": 13, "losses": 5, "record": "13-5"}, {"rank": 4, "team_name": "Birdville", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 5, "team_name": "Memorial", "wins": 15, "losses": 5, "record": "15-5"}, {"rank": 6, "team_name": "Red Oak", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 7, "team_name": "Lufkin", "wins": 14, "losses": 4, "record": "14-4"}, {"rank": 8, "team_name": "Friendswood", "wins": 17, "losses": 6, "record": "17-6"}, {"rank": 9, "team_name": "Denton", "wins": 15, "losses": 3, "record": "15-3"}, {"rank": 10, "team_name": "West Brook", "wins": 15, "losses": 3, "record": "15-3"}, {"rank": 11, "team_name": "Mansfield Timberview", "wins": 15, "losses": 3, "record": "15-3"}, {"rank": 12, "team_name": "Iowa Colony", "wins": 16, "losses": 6, "record": "16-6"}, {"rank": 13, "team_name": "Lovejoy", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 14, "team_name": "Amarillo", "wins": 15, "losses": 4, "record": "15-4"}, {"rank": 15, "team_name": "Alamo Heights", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 16, "team_name": "McAllen", "wins": 23, "losses": 0, "record": "23-0"}, {"rank": 17, "team_name": "Fort Bend Marshall", "wins": 13, "losses": 7, "record": "13-7"}, {"rank": 18, "team_name": "New Braunfels", "wins": 19, "losses": 4, "record": "19-4"}, {"rank": 19, "team_name": "Pieper", "wins": 16, "losses": 5, "record": "16-5"}, {"rank": 20, "team_name": "Veterans Memorial", "wins": 15, "losses": 5, "record": "15-5"}, {"rank": 21, "team_name": "Walnut Grove", "wins": 13, "losses": 6, "record": "13-6"}, {"rank": 22, "team_name": "Colleyville Heritage", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 23, "team_name": "Reedy", "wins": 12, "losses": 7, "record": "12-7"}, {"rank": 24, "team_name": "Liberty", "wins": 10, "losses": 7, "record": "10-7"}, {"rank": 25, "team_name": "Monterey", "wins": 16, "losses": 5, "record": "16-5"}],
        "4A": [{"rank": 1, "team_name": "Liberty", "wins": 15, "losses": 3, "record": "15-3"}, {"rank": 2, "team_name": "Canyon", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 3, "team_name": "Carter", "wins": 11, "losses": 6, "record": "11-6"}, {"rank": 4, "team_name": "Stephenville", "wins": 19, "losses": 1, "record": "19-1"}, {"rank": 5, "team_name": "Seminole", "wins": 18, "losses": 3, "record": "18-3"}, {"rank": 6, "team_name": "Wimberley", "wins": 20, "losses": 2, "record": "20-2"}, {"rank": 7, "team_name": "Burkburnett", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 8, "team_name": "West Plains", "wins": 13, "losses": 4, "record": "13-4"}, {"rank": 9, "team_name": "Kennedale", "wins": 12, "losses": 5, "record": "12-5"}, {"rank": 10, "team_name": "Estacado", "wins": 15, "losses": 4, "record": "15-4"}, {"rank": 11, "team_name": "Brock", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 12, "team_name": "Krum", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 13, "team_name": "Paris", "wins": 14, "losses": 4, "record": "14-4"}, {"rank": 14, "team_name": "Farmersville", "wins": 18, "losses": 1, "record": "18-1"}, {"rank": 15, "team_name": "Chapel Hill", "wins": 17, "losses": 1, "record": "17-1"}, {"rank": 16, "team_name": "Yates", "wins": 11, "losses": 2, "record": "11-2"}, {"rank": 17, "team_name": "La Marque", "wins": 20, "losses": 1, "record": "20-1"}, {"rank": 18, "team_name": "Wheatley", "wins": 7, "losses": 3, "record": "7-3"}, {"rank": 19, "team_name": "Almeta Crawford", "wins": 12, "losses": 6, "record": "12-6"}, {"rank": 20, "team_name": "Gainesville", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 21, "team_name": "Livingston", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 22, "team_name": "Glen Rose", "wins": 16, "losses": 5, "record": "16-5"}, {"rank": 23, "team_name": "Panther Creek", "wins": 8, "losses": 6, "record": "8-6"}, {"rank": 24, "team_name": "Kimball", "wins": 5, "losses": 8, "record": "5-8"}, {"rank": 25, "team_name": "Washington", "wins": 14, "losses": 6, "record": "14-6"}],
        "3A": [{"rank": 1, "team_name": "Westwood", "wins": 12, "losses": 1, "record": "12-1"}, {"rank": 2, "team_name": "Paradise", "wins": 19, "losses": 2, "record": "19-2"}, {"rank": 3, "team_name": "Shallowater", "wins": 13, "losses": 2, "record": "13-2"}, {"rank": 4, "team_name": "Slaton", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 5, "team_name": "London", "wins": 22, "losses": 1, "record": "22-1"}, {"rank": 6, "team_name": "Onalaska", "wins": 18, "losses": 4, "record": "18-4"}, {"rank": 7, "team_name": "Orangefield", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 8, "team_name": "Jefferson", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 9, "team_name": "Brownfield", "wins": 14, "losses": 6, "record": "14-6"}, {"rank": 10, "team_name": "East Chambers", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 11, "team_name": "Holliday", "wins": 12, "losses": 3, "record": "12-3"}, {"rank": 12, "team_name": "Village Tech", "wins": 11, "losses": 3, "record": "11-3"}, {"rank": 13, "team_name": "Liberty-Eylau", "wins": 15, "losses": 4, "record": "15-4"}, {"rank": 14, "team_name": "Cole", "wins": 17, "losses": 4, "record": "17-4"}, {"rank": 15, "team_name": "Jim Ned", "wins": 13, "losses": 4, "record": "13-4"}, {"rank": 16, "team_name": "Dalhart", "wins": 14, "losses": 2, "record": "14-2"}, {"rank": 17, "team_name": "Wall", "wins": 16, "losses": 5, "record": "16-5"}, {"rank": 18, "team_name": "Fairfield", "wins": 12, "losses": 3, "record": "12-3"}, {"rank": 19, "team_name": "Lexington", "wins": 12, "losses": 3, "record": "12-3"}, {"rank": 20, "team_name": "Ponder", "wins": 13, "losses": 7, "record": "13-7"}, {"rank": 21, "team_name": "Compass Academy", "wins": 15, "losses": 0, "record": "15-0"}, {"rank": 22, "team_name": "Keene", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 23, "team_name": "City View", "wins": 7, "losses": 5, "record": "7-5"}, {"rank": 24, "team_name": "Lamesa", "wins": 10, "losses": 4, "record": "10-4"}, {"rank": 25, "team_name": "Clyde", "wins": 15, "losses": 5, "record": "15-5"}],
        "2A": [{"rank": 1, "team_name": "Lipan", "wins": 17, "losses": 1, "record": "17-1"}, {"rank": 2, "team_name": "Martins Mill", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 3, "team_name": "Roscoe", "wins": 20, "losses": 1, "record": "20-1"}, {"rank": 4, "team_name": "Graford", "wins": 16, "losses": 1, "record": "16-1"}, {"rank": 5, "team_name": "Olton", "wins": 19, "losses": 2, "record": "19-2"}, {"rank": 6, "team_name": "Ropes", "wins": 11, "losses": 2, "record": "11-2"}, {"rank": 7, "team_name": "Hale Center", "wins": 12, "losses": 1, "record": "12-1"}, {"rank": 8, "team_name": "Chireno", "wins": 8, "losses": 3, "record": "8-3"}, {"rank": 9, "team_name": "Farwell", "wins": 13, "losses": 4, "record": "13-4"}, {"rank": 10, "team_name": "LaPoynor", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 11, "team_name": "Slidell", "wins": 13, "losses": 6, "record": "13-6"}, {"rank": 12, "team_name": "Hamilton", "wins": 4, "losses": 1, "record": "4-1"}, {"rank": 13, "team_name": "Port Aransas", "wins": 13, "losses": 5, "record": "13-5"}, {"rank": 14, "team_name": "Gary", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 15, "team_name": "Abernathy", "wins": 13, "losses": 3, "record": "13-3"}, {"rank": 16, "team_name": "Windthorst", "wins": 13, "losses": 5, "record": "13-5"}, {"rank": 17, "team_name": "Meyer", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 18, "team_name": "Nocona", "wins": 15, "losses": 2, "record": "15-2"}, {"rank": 19, "team_name": "Whitewright", "wins": 10, "losses": 1, "record": "10-1"}, {"rank": 20, "team_name": "Thorndale", "wins": 14, "losses": 4, "record": "14-4"}, {"rank": 21, "team_name": "Bartlett", "wins": 16, "losses": 3, "record": "16-3"}, {"rank": 22, "team_name": "San Augustine", "wins": 6, "losses": 3, "record": "6-3"}, {"rank": 23, "team_name": "Hearne", "wins": 14, "losses": 6, "record": "14-6"}, {"rank": 24, "team_name": "Hawkins", "wins": 11, "losses": 5, "record": "11-5"}, {"rank": 25, "team_name": "Wellington", "wins": 9, "losses": 5, "record": "9-5"}],
        "1A": [{"rank": 1, "team_name": "Huckabay", "wins": 20, "losses": 2, "record": "20-2"}, {"rank": 2, "team_name": "Texline", "wins": 13, "losses": 4, "record": "13-4"}, {"rank": 3, "team_name": "Fayetteville", "wins": 14, "losses": 5, "record": "14-5"}, {"rank": 4, "team_name": "Richards", "wins": 12, "losses": 2, "record": "12-2"}, {"rank": 5, "team_name": "Valley", "wins": 13, "losses": 3, "record": "13-3"}, {"rank": 6, "team_name": "Irion County", "wins": 11, "losses": 1, "record": "11-1"}, {"rank": 7, "team_name": "Moulton", "wins": 17, "losses": 3, "record": "17-3"}, {"rank": 8, "team_name": "Gordon", "wins": 4, "losses": 2, "record": "4-2"}, {"rank": 9, "team_name": "Buena Vista", "wins": 10, "losses": 2, "record": "10-2"}, {"rank": 10, "team_name": "Sands", "wins": 12, "losses": 4, "record": "12-4"}, {"rank": 11, "team_name": "Water Valley", "wins": 6, "losses": 2, "record": "6-2"}, {"rank": 12, "team_name": "McLean", "wins": 9, "losses": 0, "record": "9-0"}, {"rank": 13, "team_name": "Munday", "wins": 13, "losses": 8, "record": "13-8"}, {"rank": 14, "team_name": "Veribest", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 15, "team_name": "Benjamin", "wins": 8, "losses": 3, "record": "8-3"}, {"rank": 16, "team_name": "O'Donnell", "wins": 13, "losses": 4, "record": "13-4"}, {"rank": 17, "team_name": "Crosbyton", "wins": 10, "losses": 2, "record": "10-2"}, {"rank": 18, "team_name": "Robert Lee", "wins": 9, "losses": 5, "record": "9-5"}, {"rank": 19, "team_name": "Perrin-Whitt", "wins": 11, "losses": 5, "record": "11-5"}, {"rank": 20, "team_name": "Whitharral", "wins": 10, "losses": 8, "record": "10-8"}, {"rank": 21, "team_name": "D'Hanis", "wins": 16, "losses": 4, "record": "16-4"}, {"rank": 22, "team_name": "Rising Star", "wins": 6, "losses": 1, "record": "6-1"}, {"rank": 23, "team_name": "Brookeland", "wins": 9, "losses": 9, "record": "9-9"}, {"rank": 24, "team_name": "Centerville", "wins": 11, "losses": 6, "record": "11-6"}, {"rank": 25, "team_name": "Avery", "wins": 16, "losses": 6, "record": "16-6"}]
    },
    "tapps": {
        "TAPPS_6A": [{"rank": 1, "team_name": "St. Michael's", "wins": 19, "losses": 5, "record": "19-5"}, {"rank": 2, "team_name": "TMI-Episcopal", "wins": 9, "losses": 4, "record": "9-4"}, {"rank": 3, "team_name": "St. John XXIII", "wins": 18, "losses": 4, "record": "18-4"}, {"rank": 4, "team_name": "Trinity Christian", "wins": 14, "losses": 9, "record": "14-9"}, {"rank": 5, "team_name": "Village", "wins": 11, "losses": 13, "record": "11-13"}, {"rank": 6, "team_name": "Liberty Christian", "wins": 9, "losses": 15, "record": "9-15"}, {"rank": 7, "team_name": "Cathedral", "wins": 11, "losses": 8, "record": "11-8"}, {"rank": 8, "team_name": "Concordia Lutheran", "wins": 15, "losses": 12, "record": "15-12"}, {"rank": 9, "team_name": "Savio", "wins": 8, "losses": 12, "record": "8-12"}],
        "TAPPS_5A": [{"rank": 1, "team_name": "Trinity Christian", "wins": 17, "losses": 5, "record": "17-5"}, {"rank": 2, "team_name": "Fort Bend Christian Academy", "wins": 14, "losses": 13, "record": "14-13"}, {"rank": 3, "team_name": "Kelly Catholic", "wins": 13, "losses": 11, "record": "13-11"}, {"rank": 4, "team_name": "Emery/Weiner", "wins": 5, "losses": 8, "record": "5-8"}, {"rank": 5, "team_name": "Hyde Park", "wins": 12, "losses": 12, "record": "12-12"}, {"rank": 6, "team_name": "Bishop Dunne", "wins": 5, "losses": 14, "record": "5-14"}, {"rank": 7, "team_name": "Legacy Prep Christian Academy", "wins": 6, "losses": 10, "record": "6-10"}, {"rank": 8, "team_name": "St. Augustine", "wins": 4, "losses": 15, "record": "4-15"}, {"rank": 9, "team_name": "San Antonio Christian", "wins": 6, "losses": 17, "record": "6-17"}, {"rank": 10, "team_name": "Saint Mary's Hall", "wins": 2, "losses": 15, "record": "2-15"}],
        "TAPPS_4A": [{"rank": 1, "team_name": "Westbury Christian", "wins": 17, "losses": 6, "record": "17-6"}, {"rank": 2, "team_name": "Covenant Christian", "wins": 11, "losses": 4, "record": "11-4"}, {"rank": 3, "team_name": "Bishop Gorman", "wins": 13, "losses": 6, "record": "13-6"}, {"rank": 4, "team_name": "St. Thomas Episcopal", "wins": 13, "losses": 6, "record": "13-6"}, {"rank": 5, "team_name": "Lubbock Christian", "wins": 7, "losses": 4, "record": "7-4"}, {"rank": 6, "team_name": "The Christian School at Castle Hills", "wins": 23, "losses": 6, "record": "23-6"}, {"rank": 7, "team_name": "Texas School for the Deaf", "wins": 7, "losses": 3, "record": "7-3"}, {"rank": 8, "team_name": "Veritas Academy", "wins": 9, "losses": 9, "record": "9-9"}, {"rank": 9, "team_name": "Dallas Christian", "wins": 9, "losses": 12, "record": "9-12"}, {"rank": 10, "team_name": "Prince of Peace", "wins": 12, "losses": 12, "record": "12-12"}],
        "TAPPS_3A": [{"rank": 1, "team_name": "Live Oak Classical", "wins": 17, "losses": 4, "record": "17-4"}, {"rank": 2, "team_name": "Alpha Omega Academy", "wins": 7, "losses": 1, "record": "7-1"}, {"rank": 3, "team_name": "Heritage Christian", "wins": 8, "losses": 2, "record": "8-2"}, {"rank": 4, "team_name": "Lakehill Prep", "wins": 11, "losses": 3, "record": "11-3"}, {"rank": 5, "team_name": "Covenant Classical", "wins": 8, "losses": 10, "record": "8-10"}, {"rank": 6, "team_name": "Central Texas Christian", "wins": 9, "losses": 5, "record": "9-5"}, {"rank": 7, "team_name": "Yavneh Academy", "wins": 4, "losses": 7, "record": "4-7"}, {"rank": 8, "team_name": "Keystone", "wins": 3, "losses": 2, "record": "3-2"}, {"rank": 9, "team_name": "Abilene Christian", "wins": 7, "losses": 10, "record": "7-10"}, {"rank": 10, "team_name": "Covenant Christian", "wins": 7, "losses": 4, "record": "7-4"}],
        "TAPPS_2A": [{"rank": 1, "team_name": "First Baptist", "wins": 7, "losses": 3, "record": "7-3"}, {"rank": 2, "team_name": "Victory Christian Academy", "wins": 12, "losses": 4, "record": "12-4"}, {"rank": 3, "team_name": "Holy Cross Catholic Academy", "wins": 9, "losses": 7, "record": "9-7"}, {"rank": 4, "team_name": "Ascension Academy", "wins": 10, "losses": 4, "record": "10-4"}, {"rank": 5, "team_name": "Garland Christian Academy", "wins": 7, "losses": 5, "record": "7-5"}, {"rank": 6, "team_name": "Nazarene Christian Academy", "wins": 14, "losses": 7, "record": "14-7"}, {"rank": 7, "team_name": "Faith Academy", "wins": 17, "losses": 4, "record": "17-4"}, {"rank": 8, "team_name": "Sacred Heart", "wins": 3, "losses": 2, "record": "3-2"}, {"rank": 9, "team_name": "Bracken Christian", "wins": 12, "losses": 7, "record": "12-7"}, {"rank": 10, "team_name": "Valor Preparatory Academy", "wins": 5, "losses": 4, "record": "5-4"}],
        "TAPPS_1A": [{"rank": 1, "team_name": "The Covenant Preparatory School", "wins": 14, "losses": 2, "record": "14-2"}, {"rank": 2, "team_name": "Divine Savior Academy - Sienna", "wins": 10, "losses": 1, "record": "10-1"}, {"rank": 3, "team_name": "Harvest Christian", "wins": 21, "losses": 6, "record": "21-6"}, {"rank": 4, "team_name": "Founders Christian", "wins": 15, "losses": 4, "record": "15-4"}, {"rank": 5, "team_name": "Christ Academy", "wins": 8, "losses": 3, "record": "8-3"}, {"rank": 6, "team_name": "Cornerstone Christian Academy", "wins": 6, "losses": 4, "record": "6-4"}, {"rank": 7, "team_name": "Lifestyle Christian", "wins": 8, "losses": 6, "record": "8-6"}, {"rank": 8, "team_name": "Regents Academy", "wins": 5, "losses": 6, "record": "5-6"}, {"rank": 9, "team_name": "Faith Academy", "wins": 2, "losses": 4, "record": "2-4"}, {"rank": 10, "team_name": "First Baptist Academy", "wins": 7, "losses": 10, "record": "7-10"}]
    }
}

# Load existing weekly rankings
with open('data/weekly_rankings_20260105.json', 'r') as f:
    weekly_rankings = json.load(f)

# Merge MaxPreps data
weekly_rankings['maxpreps'] = maxpreps_data

# Update timestamp
weekly_rankings['date'] = datetime.now().isoformat()

# Save merged data
with open('data/weekly_rankings_20260105.json', 'w') as f:
    json.dump(weekly_rankings, f, indent=2)

print("✓ Merged MaxPreps data into weekly rankings file")
print(f"  UIL 6A: {len(maxpreps_data['uil']['6A'])} teams")
print(f"  UIL 5A: {len(maxpreps_data['uil']['5A'])} teams")
print(f"  UIL 4A: {len(maxpreps_data['uil']['4A'])} teams")
print(f"  UIL 3A: {len(maxpreps_data['uil']['3A'])} teams")
print(f"  UIL 2A: {len(maxpreps_data['uil']['2A'])} teams")
print(f"  UIL 1A: {len(maxpreps_data['uil']['1A'])} teams")
print(f"  TAPPS 6A: {len(maxpreps_data['tapps']['TAPPS_6A'])} teams")
print(f"  TAPPS 5A: {len(maxpreps_data['tapps']['TAPPS_5A'])} teams")
print(f"  TAPPS 4A: {len(maxpreps_data['tapps']['TAPPS_4A'])} teams")
print(f"  TAPPS 3A: {len(maxpreps_data['tapps']['TAPPS_3A'])} teams")
print(f"  TAPPS 2A: {len(maxpreps_data['tapps']['TAPPS_2A'])} teams")
print(f"  TAPPS 1A: {len(maxpreps_data['tapps']['TAPPS_1A'])} teams")
